### ISSUE TITLE
multiple id's on one test are not reported to testrail

### ISSUE THREAD

**Issue by pinim** [billylam/wdio-wdiov5testrail-reporter#13]
in the last version (1.0.31) you add handler for wdio retries, but the logic is wrong and cause a bug,
because we have the option handle multiply case id's in the same test, all of theme hase the same '.start' value, and they are removed even though they belong to the same retry,

**Comment by billylam** [comment]
Okay, try 1.0.32 and let me know what you see.

**Comment by pinim** [comment]
cool, work perfect! thanks.
