### ISSUE TITLE
Reporter failed

### ISSUE THREAD

**Issue by syedaqanjum** [billylam/wdio-wdiov5testrail-reporter#2]
Hi, 
I have modified my wdio.conf but keep getting the following error - 

'Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter.html)\n"

**Comment by billylam** [comment]
That is thrown by webdriverio when it can't parse your reporters.  Please double-check the reporters section in your conf.  If still an issue, paste the section and reopen.
