### ISSUE TITLE
Log invalid case ids when strictCaseMatching set to true

### ISSUE THREAD

**Issue by hdesai-dave** [billylam/wdio-wdiov5testrail-reporter#20]

**Comment by hdesai-dave** [comment]
@billylam any thoughts here? Can we get the above PR merged?

**Comment by billylam** [comment]
Thanks for the reminder.  I'll take a look.  Unfortunately my npm 2fa is failing for some reason so publishing might be a few days from now.

**Comment by hdesai-dave** [comment]
> Thanks for the reminder. I'll take a look. Unfortunately my npm 2fa is failing for some reason so publishing might be a few days from now.

If we can get the pr reviewed meanwhile, that would be great!

**Comment by billylam** [comment]
I have already reviewed and left comments.

**Comment by hdesai-dave** [comment]
> I have already reviewed and left comments.

Do not see any comments https://github.com/billylam/wdio-wdiov5testrail-reporter/pull/21/files https://github.com/shubham0803 do you see on your end?

**Comment by shubham0803** [comment]
> > I have already reviewed and left comments.
> 
> Do not see any comments https://github.com/billylam/wdio-wdiov5testrail-reporter/pull/21/files https://github.com/shubham0803 do you see on your end?

I am also not able to see any review comments on the PR

**Comment by billylam** [comment]
Are you looking at the conversation tab?  https://github.com/billylam/wdio-wdiov5testrail-reporter/pull/21

<img width="904" alt="image" src="https://user-images.githubusercontent.com/3700437/233189218-b352426d-73f1-4e6d-afc1-96edc75444af.png">

**Comment by hdesai-dave** [comment]
> Are you looking at the conversation tab? #21
> 
> <img alt="image" width="904" src="https://user-images.githubusercontent.com/3700437/233189218-b352426d-73f1-4e6d-afc1-96edc75444af.png">

Your comment Status is pending. Need to submit.

**Comment by billylam** [comment]
Ah, thanks.
