### ISSUE TITLE
We are still seeing issues with results not being updated in testrails

### ISSUE THREAD

**Issue by hdesai-dave** [billylam/wdio-wdiov5testrail-reporter#7]
* When we run smoke tests in parallel, the results are being updated just fine since it is a smaller subset. 8 spec files, 20 some test cases
* When we run full regression suite in parallel results are not updated in testrails: 200+ specs, 400+ test cases.

Any help appreciated debugging it locally or otherwise

**Comment by billylam** [comment]
TestRail just changed their API for certain calls.  Are you using the newest version (1.0.29)?

**Comment by hdesai-dave** [comment]
Yes @billylam and our previous reporter also broke after new testrail update hence trying yours.

**Comment by billylam** [comment]
Hmm, ok.  How many actual cases are marked in the testrail report?  And if you make a call to yourdomain.testrail.com/index.php?/api/v2/get_cases/[yourprojectid]&suite_id=[yoursuiteid], are the cases that are marked the ones present in that api call and the ones that are not marked the ones that are not present?

Also, are you setting a value for the `strictCaseMatching` config option?  If you are, try deleting that key or setting it to true.

**Comment by hdesai-dave** [comment]
I get 0 results updated to testrails. I do not use strictCaseMatching.

**Comment by billylam** [comment]
Do you see any error logging thrown by the reporter?  Something like

"Server responded to yourdomain.testrail.com/index.php?/api/v2/add_results_for_cases/with status code 400:"

Also try strictCaseMatching: false.  If that works, the issue is that you have a test case mismatch.

**Comment by hdesai-dave** [comment]
No errors in logs!

**Comment by billylam** [comment]
Please try the other options listed above.  They will show if you have an issue with test cases in webdriverio not matching those in TestRail, which will cause this type of error.

> Also try strictCaseMatching: false. If that works, the issue is that you have a test case mismatch.

> Hmm, ok. How many actual cases are marked in the testrail report? And if you make a call to yourdomain.testrail.com/index.php?/api/v2/get_cases/[yourprojectid]&suite_id=[yoursuiteid], are the cases that are marked the ones present in that api call and the ones that are not marked the ones that are not present?

**Comment by hdesai-dave** [comment]
Yeah strictCaseMatching: false worked. How do i find the mismatch now 🤦‍♂️

**Comment by hdesai-dave** [comment]
Thanks for your prompt response!
