### ISSUE TITLE
For some reason start return Cannot read property 'id' of undefined for run id from getRuns 

### ISSUE THREAD

**Issue by djamknacker** [billylam/wdio-wdiov5testrail-reporter#8]
This line
`options.runId = JSON.parse(response.getBody())[0].id;`

Returns this error: 
`ERROR @wdio/cli:utils: Error in onCompleteHook: TypeError: Cannot read property 'id' of undefined
    at /Users/autotests/tests/node_modules/wdio-wdiov5testrail-reporter/src/util.js:113:56
`

I can see that there is a body (buffer) being returned by getRuns so I guess it is not parsing it correctly

**Comment by billylam** [comment]
Thanks for reporting the issue.  TestRail changed the data shape for some of their api calls a few months ago, and I missed one that is called when using useLatestRunId.  This should be fixed in 1.0.30, but reopen if you are still seeing an issue.

**Comment by djamknacker** [comment]
@billylam thanks for fix. 
Can confirm it works now
